install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("tidyverse", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("topicmodels", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("reshape2", repos='http://cran.us.r-project.org', dependencies=TRUE)
require(devtools)
install_version("quanteda", version = "1.4.0", repos='http://cran.us.r-project.org', dependencies=TRUE)
