install.packages("tidyverse", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("stm", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("quanteda", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("topicmodels", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("reshape2", repos='http://cran.us.r-project.org', dependencies=TRUE)
